### ISSUE TITLE
ПР4 (ломаная линия)

### ISSUE THREAD

**Issue by drxaos** [7yon/Java#1]
1. getCoordinates() и outCoordinates() - в джаве обычно для перевода объекта в строку служит метод toString. Если код перевода не делает ничего "тяжелого" (типа обращения к файлам или к бд), то лучше переопределить им стандартный toString().
2. Аналогично вместо comparison() лучше переопределить стандартный equals().
3. В классе Point префикс "_" у названий переменных не несет никакой пользы, а только добавляет визуальный шум.

**Comment by 7yon** [comment]
fixed 996cae23b4d2aee3042296ba0f26a3fe8c4594fc

**Comment by drxaos** [comment]
Сравнение двух точек теперь не работает. "this == obj" проверяет, что это один и тот же объект

**Comment by 7yon** [comment]
804a7d1b550d8ba1794e811ece8a4bf28f8ac011
